CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ID VARCHAR(50) NOT NULL,
    OWNER_NAME VARCHAR(100) NOT NULL,
    BALANCE DECIMAL(65, 8) NOT NULL,
    CURRENCY_CODE VARCHAR(3) NOT NULL,
    CREATED_DATE_TIME DATETIME(6) NOT NULL,
    UPDATED_DATE_TIME DATETIME(6) NOT NULL,
    VERSION BIGINT NOT NULL,
    CONSTRAINT pk_accounts_id PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;