CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID VARCHAR(50) NOT NULL,
    FROM_ACCOUNT_ID VARCHAR(50) NOT NULL,
    TO_ACCOUNT_ID VARCHAR(50) NOT NULL,
    AMOUNT DECIMAL(65, 8) NOT NULL,
    CURRENCY_CODE VARCHAR(3) NOT NULL,
    BUSINESS_DATE_TIME DATETIME(6) NOT NULL,
    CREATED_DATE_TIME DATETIME(6) NOT NULL,
    CONSTRAINT pk_transactions_id PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

ALTER TABLE TRANSACTIONS
  ADD INDEX transactions_from_account_time_index (FROM_ACCOUNT_ID, BUSINESS_DATE_TIME);

ALTER TABLE TRANSACTIONS
  ADD INDEX transactions_to_account_time_index (TO_ACCOUNT_ID, BUSINESS_DATE_TIME);