/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-library-conventions")
}

tasks.named<Jar>("jar") { archiveFileName.set("example-domain-core.jar") }

dependencies {
    // ## Functional Programming ##
    implementation(libs.arrow.core)

    // ## Validation ##
    implementation(libs.ktor.server.request.validation)

    // ## Logging ##
    implementation(libs.logback.classic)

    // ## Testing ##
    testImplementation(libs.kotlin.test.junit)
}
