/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-library-conventions")
}

tasks.jar {
    archiveFileName.set("example-domain-infrastructure.jar")
}

dependencies {
    implementation(project(":example-domain:domain"))
    implementation(project(":example-domain:core"))

    // ## ktor core ##
    implementation(libs.ktor.server.core.jvm)

    // ## Functional Programming ##
    implementation(libs.arrow.core)

    // ## DB ##
    api(libs.exposed.core) // For the Adapter layer to access transactions
    implementation(libs.exposed.jdbc)
    implementation(libs.exposed.dao)
    implementation(libs.exposed.kotlin.datetime)

    // Required to work with datetime in DB
    implementation(libs.hikari.cp)
    implementation(libs.mysql.connector.java)

    // Flyway
    implementation(libs.flyway.core)
    implementation(libs.flyway.mysql)

    // ## Testing ##
    testImplementation(libs.kotlin.test.junit)
}
